### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by tindzk** [sparsetech/trail#16]
We should support query parameters. Proposal:

```scala
val export = Root / "export" / Arg[Long] ? Param[Long]("user") & Param[Option[Int]]("limit")
```

This will match:

* `/export/42?user=23`
* `/export/42?user=23&limit=10`

**Comment by anatoliykmetyuk** [comment]
Two problems with this:

- If `GET` information is supported, `POST` should be supported too, and the multipart data. This requires a more sophisticated approach IMO.
- You said you do not what it http-specific - and `GET` is http-specific request type.

What you propose is useful, but maybe it is not a good idea to hard-code it. Maybe a better approach is to define an extensibility mechanism and build upon the core functionality to introduce this.

**Comment by tindzk** [comment]
Note that query parameters are not HTTP-specific. You can also specify these parameters with POST requests.

The idea of MetaRouter is to be entirely protocol-agnostic and to support URIs:
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

So far we only consider paths, but we might also want to support different schemes, hosts etc. in the future.

**Comment by anatoliykmetyuk** [comment]
Ok, I see. Looks good then.
