### ISSUE TITLE
Reduce url string parsing burden

### ISSUE THREAD

**Issue by aappddeevv** [sparsetech/trail#25]
It looks like each unapply that is used to for a route parses the url independently of others. While I don't think this is a huge burden, if this is true, I'm claiming it would be nice to have a way to parse the url string once and then re-use that parsing in each unapply (case statement).

**Comment by tindzk** [comment]
Agreed. We could introduce a helper function `Route.parse()` which returns an intermediate representation. The pattern matching block would then look as follows:

```scala
Route.parse("/user/hello?show=false") match {
  case details(a :: HNil) =>  // ...
  // ...
}
```

So routes will not match on strings anymore, only on the return value of `parse()`.

**Comment by aappddeevv** [comment]
I'd be Ok with that.

I would like to be able to map my own "string" into it though. My router
has an interface that produces a semi-parsed data structure already so as
long as I can map into whatever is used that would be great. Not critical
though, just trying to avoid full parses. I have ~50 routes (small app) and
I'm trying to avoid that on ever route render. I know its not huge but I'm
watching my renders and processing everywhere on the critical path.

**Comment by tindzk** [comment]
I have overloaded all user-facing functions with a `Path` parameter. This allows you to populate the `Path` case class with your own data.

**Comment by aappddeevv** [comment]
Thanks will give that a try!
